services:
  web:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: web_app
    command: gunicorn project.wsgi:application --bind 0.0.0.0:14005
    ports:
      - "14005:14005"
    depends_on:
      redis:
        condition: service_healthy
    volumes:
      - ./backend:/app 
    environment:
      - DJANGO_SETTINGS_MODULE=project.settings

  worker:
    build:
      context: ./backend 
      dockerfile: Dockerfile
    container_name: celery_worker
    command: celery -A project worker --loglevel=info
    depends_on:
      redis:
        condition: service_healthy
    volumes:
      - ./backend:/app 
    environment:
      - DJANGO_SETTINGS_MODULE=project.settings

  redis:
    image: redis:7-alpine
    container_name: redis
    ports:
      - "6305:6305"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5
  
  admin_web:
    build:
      context: ./admin_panel_jocely
      dockerfile: Dockerfile
    image: jocely_dashboard:dev
    container_name: jocely_dashboard
    ports:
      - "14006:14006"
    volumes:
      - ./admin_panel_jocely:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    restart: unless-stopped
